name: MyAgent
hierarchy:
  blocks:
    - name: SensoryInputBlock
      htm:  !include blocks/SensoryInputBlock.yml
      phase: 1
      substitutions:
        - region: spatialpooler
          with: HighLevelProcessingBlock.spatialpooler.bottomUpIn

    - name: HighLevelProcessingBlock
      htm:  !include blocks/HighLevelProcessingBlock.yml
      phase: 1

    - name: IntrinsicMotivationModule
      htm:  !include blocks/IntrinsicMotivationBlock.yml
      phase: 2

    - name: ActionSelectionBlock
      htm:  !include blocks/ActionSelectionBlock.yml
      phase: 2

  connections:
    - type:   default
      source: SensoryInputBlock
      target: HighLevelProcessingBlock

    - type:   lateral
      source: HighLevelProcessingBlock
      target: IntrinsicMotivationModule

    - source: IntrinsicMotivationModule
      target: ActionSelectionBlock

