# Description: This is a simple agent configuration file.
agent:
    name: simple_agent # Name of the agent
    blocks:
        - name: InputBlock # refers to the name of the block in configs/blocks/input_block.yml
            path: configs/blocks/input_block.yml # path to the block configuration file
            order: 1 # order of the block execution by the agents scheduler
        - name: ProcessingBlock 
            path: configs/blocks/processing_block.yml
            order: 2
        - name: OutputBlock
            path: configs/blocks/output_block.yml
            order: 3
        modules:
        - name: InputModule
            config: configs/modules/input_module.yml
    connections: # connections between blocks and modules
        - source: InputBlock
            destination: ProcessingBlock
        - source: ProcessingBlock
            destination: OutputBlock
    actions:
    - name: action_name_1
        type: movement
        attributes:
        direction:
            type: enum
            values:
            - forward
            - backward
        speed:
            type: scalar
                minValue: 0
                maxValue: 1.0
    - name: action_name_2
        type: manipulation
        attributes:
        operation:
            type: enum
            values:
            - grasping
            - lifting
        force:
            type: scalar
            minValue: 10
            maxValue: 50
        object_size:
            type: vector
            minValues:
                x: 0
                y: 0
            maxValues:
                x: 10
                y: 10
    - name: action_name_4
        type: communication
        attributes:
        communication_range:
            type: scalar
            minValue: 0
            maxValue: 100
        data_rate:
            type: scalar
            minValue: 1
            maxValue: 10
